# -*- coding: utf-8 -*-
"""GenAi_internship_Task 4_Code.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xLhQfVX0sfLopxFKkhFFK95d0RTD4wsP

Libraries
"""


"""Tokenization (BERT Tokenizer)"""

from transformers import BertTokenizer

tokenizer = BertTokenizer.from_pretrained("bert-base-uncased")

text = "AI is transforming the world"

tokens = tokenizer.tokenize(text)
ids = tokenizer.encode(text)

print("Tokens:", tokens)
print("Token IDs:", ids)

"""GPT-style Tokenization (BPE)"""

from transformers import GPT2Tokenizer

tokenizer = GPT2Tokenizer.from_pretrained("gpt2")

text = "Tokenization is very important in NLP"

tokens = tokenizer.tokenize(text)
ids = tokenizer.encode(text)

print("Tokens:", tokens)
print("IDs:", ids)

"""SentencePiece (T5 Model)"""

from transformers import T5Tokenizer

tokenizer = T5Tokenizer.from_pretrained("t5-small")

text = "Machine learning is amazing"

tokens = tokenizer.tokenize(text)
ids = tokenizer.encode(text)

print("Tokens:", tokens)
print("IDs:", ids)

"""Simple Embedding Example"""

from transformers import BertModel, BertTokenizer
import torch

tokenizer = BertTokenizer.from_pretrained("bert-base-uncased")
model = BertModel.from_pretrained("bert-base-uncased")

text = "AI is powerful"
inputs = tokenizer(text, return_tensors="pt")

with torch.no_grad():
    outputs = model(**inputs)

embeddings = outputs.last_hidden_state

print("Embedding shape:", embeddings.shape)

"""### Deploying on Streamlit

To deploy this as a Streamlit application, you'll need to create a Python file (e.g., `app.py`) with the following code. Streamlit allows you to build interactive web apps with pure Python.
"""

pip install streamlit

import streamlit as st
from transformers import BertTokenizer, GPT2Tokenizer, T5Tokenizer, BertModel
import torch

st.set_page_config(layout="wide", page_title="NLP with Hugging Face")
st.title("NLP Demonstrator: Tokenization and Embeddings")

st.markdown("This application demonstrates different tokenization methods and how to generate embeddings using Hugging Face's `transformers` library.")

# User Input
user_text = st.text_area("Enter your text here:", "AI is transforming the world and Tokenization is very important in NLP. Machine learning is amazing.")

if user_text:
    st.header("1. Tokenization Examples")

    st.subheader("BERT Tokenization (bert-base-uncased)")
    with st.spinner('Loading BERT Tokenizer...'):
        bert_tokenizer = BertTokenizer.from_pretrained("bert-base-uncased")
    bert_tokens = bert_tokenizer.tokenize(user_text)
    bert_ids = bert_tokenizer.encode(user_text, add_special_tokens=True)
    st.write(f"**Original Text:** `{user_text}`")
    st.write(f"**Tokens:** `{bert_tokens}`")
    st.write(f"**Token IDs (with special tokens):** `{bert_ids}`")

    st.subheader("GPT-2 Tokenization (gpt2)")
    with st.spinner('Loading GPT-2 Tokenizer...'):
        gpt2_tokenizer = GPT2Tokenizer.from_pretrained("gpt2")
    gpt2_tokens = gpt2_tokenizer.tokenize(user_text)
    gpt2_ids = gpt2_tokenizer.encode(user_text, add_special_tokens=True)
    st.write(f"**Original Text:** `{user_text}`")
    st.write(f"**Tokens:** `{gpt2_tokens}`")
    st.write(f"**Token IDs (with special tokens):** `{gpt2_ids}`")

    st.subheader("T5 Tokenization (t5-small)")
    with st.spinner('Loading T5 Tokenizer...'):
        t5_tokenizer = T5Tokenizer.from_pretrained("t5-small")
    t5_tokens = t5_tokenizer.tokenize(user_text)
    t5_ids = t5_tokenizer.encode(user_text, add_special_tokens=True)
    st.write(f"**Original Text:** `{user_text}`")
    st.write(f"**Tokens:** `{t5_tokens}`")
    st.write(f"**Token IDs (with special tokens):** `{t5_ids}`")

    st.header("2. Embedding Example (BERT)")
    st.markdown("This will generate contextual embeddings for your input text using a pre-trained `bert-base-uncased` model.")

    with st.spinner('Loading BERT Model and generating embeddings...'):
        # Reuse bert_tokenizer from above or load again if this section was standalone
        if 'bert_tokenizer' not in locals():
            bert_tokenizer = BertTokenizer.from_pretrained("bert-base-uncased")
        bert_model = BertModel.from_pretrained("bert-base-uncased")

        inputs = bert_tokenizer(user_text, return_tensors="pt", truncation=True, padding=True)

        with torch.no_grad():
            outputs = bert_model(**inputs)

        embeddings = outputs.last_hidden_state

    st.write(f"**Input Text:** `{user_text}`")
    st.write(f"**Embedding shape:** `{embeddings.shape}` (Batch Size, Sequence Length, Hidden Size)")
    st.write("The \"Hidden Size\" (768 in this case) represents the dimensionality of the vector that captures the meaning of each token in its context.")
    st.write("**Example (first token embedding - first 10 dimensions):**")
    st.code(embeddings[0, 0, :10].tolist(), language='python')
else:
    st.info("Please enter some text to see the NLP demonstrations.")

"""```python
import streamlit as st
from transformers import BertTokenizer, GPT2Tokenizer, T5Tokenizer, BertModel
import torch

st.set_page_config(layout="wide", page_title="NLP with Hugging Face")
st.title("NLP Demonstrator: Tokenization and Embeddings")

st.markdown("This application demonstrates different tokenization methods and how to generate embeddings using Hugging Face's `transformers` library.")

# --- Model Loading (Cached to prevent re-loading on every rerun) ---
@st.cache_resource
def load_bert_tokenizer():
    return BertTokenizer.from_pretrained("bert-base-uncased")

@st.cache_resource
def load_gpt2_tokenizer():
    return GPT2Tokenizer.from_pretrained("gpt2")

@st.cache_resource
def load_t5_tokenizer():
    return T5Tokenizer.from_pretrained("t5-small")

@st.cache_resource
def load_bert_model():
    return BertModel.from_pretrained("bert-base-uncased")

bert_tokenizer = load_bert_tokenizer()
gpt2_tokenizer = load_gpt2_tokenizer()
t5_tokenizer = load_t5_tokenizer()
bert_model = load_bert_model()

# --- User Input/Dataset Options ---
st.header("Input Text for Analysis")
input_option = st.radio(
    "Choose input method:",
    ("Enter Custom Text", "Use Sample Sentences")
)

texts_to_process = []
if input_option == "Enter Custom Text":
    custom_text = st.text_area(
        "Enter sentences (one per line) or a single paragraph:",
        "AI is transforming the world.\nTokenization is very important in NLP.\nMachine learning is amazing."
    )
    if custom_text:
        texts_to_process = [line.strip() for line in custom_text.splitlines() if line.strip()]
    if not texts_to_process and custom_text.strip(): # Fallback if splitlines yields empty but text is present
        texts_to_process = [custom_text.strip()]
    if not texts_to_process:
        st.info("Please enter some text.")

elif input_option == "Use Sample Sentences":
    sample_texts = [
        "Artificial intelligence is rapidly advancing.",
        "Natural Language Processing powers many modern applications.",
        "Understanding text data is crucial for AI.",
        "Hugging Face provides excellent tools for NLP."
    ]
    selected_sample = st.selectbox(
        "Select a sample sentence:",
        sample_texts
    )
    if selected_sample:
        texts_to_process = [selected_sample]

if texts_to_process:
    for i, text in enumerate(texts_to_process):
        st.subheader(f"Analysis for Text {i+1}: \"{text}\"")

        st.markdown("### 1. Tokenization Examples")

        # BERT
        st.markdown("#### BERT Tokenization (bert-base-uncased)")
        bert_tokens = bert_tokenizer.tokenize(text)
        bert_ids = bert_tokenizer.encode(text, add_special_tokens=True)
        st.write(f"**Tokens:** `{bert_tokens}`")
        st.write(f"**Token IDs (with special tokens):** `{bert_ids}`")

        # GPT-2
        st.markdown("#### GPT-2 Tokenization (gpt2)")
        gpt2_tokens = gpt2_tokenizer.tokenize(text)
        gpt2_ids = gpt2_tokenizer.encode(text, add_special_tokens=True)
        st.write(f"**Tokens:** `{gpt2_tokens}`")
        st.write(f"**Token IDs (with special tokens):** `{gpt2_ids}`")

        # T5
        st.markdown("#### T5 Tokenization (t5-small)")
        t5_tokens = t5_tokenizer.tokenize(text)
        t5_ids = t5_tokenizer.encode(text, add_special_tokens=True)
        st.write(f"**Tokens:** `{t5_tokens}`")
        st.write(f"**Token IDs (with special tokens):** `{t5_ids}`")

        st.markdown("### 2. Embedding Example (BERT)")
        inputs = bert_tokenizer(text, return_tensors="pt", truncation=True, padding=True)
        with torch.no_grad():
            outputs = bert_model(**inputs)
        embeddings = outputs.last_hidden_state
        st.write(f"**Embedding shape:** `{embeddings.shape}` (Batch Size, Sequence Length, Hidden Size)")
        st.write("The \"Hidden Size\" (768) captures the meaning of each token in its context.")
        st.write("**Example (first token embedding - first 10 dimensions):**")
        st.code(embeddings[0, 0, :10].tolist(), language='python')

# --- Show Code Option ---
st.header("View Application Code")
if st.checkbox("Show app.py code"): # This displays the code of the app itself
    st.code(
        '''
import streamlit as st
from transformers import BertTokenizer, GPT2Tokenizer, T5Tokenizer, BertModel
import torch

st.set_page_config(layout="wide", page_title="NLP with Hugging Face")
st.title("NLP Demonstrator: Tokenization and Embeddings")

st.markdown("This application demonstrates different tokenization methods and how to generate embeddings using Hugging Face's `transformers` library.")

# --- Model Loading (Cached to prevent re-loading on every rerun) ---
@st.cache_resource
def load_bert_tokenizer():
    return BertTokenizer.from_pretrained("bert-base-uncased")

@st.cache_resource
def load_gpt2_tokenizer():
    return GPT2Tokenizer.from_pretrained("gpt2")

@st.cache_resource
def load_t5_tokenizer():
    return T5Tokenizer.from_pretrained("t5-small")

@st.cache_resource
def load_bert_model():
    return BertModel.from_pretrained("bert-base-uncased")

bert_tokenizer = load_bert_tokenizer()
gpt2_tokenizer = load_gpt2_tokenizer()
t5_tokenizer = load_t5_tokenizer()
bert_model = load_bert_model()

# --- User Input/Dataset Options ---
st.header("Input Text for Analysis")
input_option = st.radio(
    "Choose input method:",
    ("Enter Custom Text", "Use Sample Sentences")
)

texts_to_process = []
if input_option == "Enter Custom Text":
    custom_text = st.text_area(
        "Enter sentences (one per line) or a single paragraph:",
        "AI is transforming the world.\nTokenization is very important in NLP.\nMachine learning is amazing."
    )
    if custom_text:
        texts_to_process = [line.strip() for line in custom_text.splitlines() if line.strip()]
    if not texts_to_process and custom_text.strip():
        texts_to_process = [custom_text.strip()]
    if not texts_to_process:
        st.info("Please enter some text.")

elif input_option == "Use Sample Sentences":
    sample_texts = [
        "Artificial intelligence is rapidly advancing.",
        "Natural Language Processing powers many modern applications.",
        "Understanding text data is crucial for AI.",
        "Hugging Face provides excellent tools for NLP."
    ]
    selected_sample = st.selectbox(
        "Select a sample sentence:",
        sample_texts
    )
    if selected_sample:
        texts_to_process = [selected_sample]

if texts_to_process:
    for i, text in enumerate(texts_to_process):
        st.subheader(f"Analysis for Text {i+1}: \"{text}\"")

        st.markdown("### 1. Tokenization Examples")

        # BERT
        st.markdown("#### BERT Tokenization (bert-base-uncased)")
        bert_tokens = bert_tokenizer.tokenize(text)
        bert_ids = bert_tokenizer.encode(text, add_special_tokens=True)
        st.write(f"**Tokens:** `{bert_tokens}`")
        st.write(f"**Token IDs (with special tokens):** `{bert_ids}`")

        # GPT-2
        st.markdown("#### GPT-2 Tokenization (gpt2)")
        gpt2_tokens = gpt2_tokenizer.tokenize(text)
        gpt2_ids = gpt2_tokenizer.encode(text, add_special_tokens=True)
        st.write(f"**Tokens:** `{gpt2_tokens}`")
        st.write(f"**Token IDs (with special tokens):** `{gpt2_ids}`")

        # T5
        st.markdown("#### T5 Tokenization (t5-small)")
        t5_tokens = t5_tokenizer.tokenize(text)
        t5_ids = t5_tokenizer.encode(text, add_special_tokens=True)
        st.write(f"**Tokens:** `{t5_tokens}`")
        st.write(f"**Token IDs (with special tokens):** `{t5_ids}`")

        st.markdown("### 2. Embedding Example (BERT)")
        inputs = bert_tokenizer(text, return_tensors="pt", truncation=True, padding=True)
        with torch.no_grad():
            outputs = bert_model(**inputs)
        embeddings = outputs.last_hidden_state
        st.write(f"**Embedding shape:** `{embeddings.shape}` (Batch Size, Sequence Length, Hidden Size)")
        st.write("The \"Hidden Size\" (768) captures the meaning of each token in its context.")
        st.write("**Example (first token embedding - first 10 dimensions):**")
        st.code(embeddings[0, 0, :10].tolist(), language='python')
        ''',
        language="python"
    )

```

### How to Run Your Streamlit App:

1.  **Save the code:** Copy the Python code from the cell above and save it into a file named `app.py` on your local machine.
2.  **Install Streamlit:** If you haven't already, install Streamlit in your environment (once is enough!):
    ```bash
    pip install streamlit transformers torch
    ```
    (You've already installed these in Colab, but you'd need to do this in your local environment if running there for the first time.)
3.  **Run the app:** Open your terminal or command prompt, navigate to the directory where you saved `app.py`, and run the following command:
    ```bash
    streamlit run app.py
    ```
4.  **Access the app:** Streamlit will then open a new tab in your web browser with your interactive NLP application, including the dataset options and the ability to view the code.

### How to Run Your Streamlit App:

1.  **Save the code:** Copy the Python code from the cell above and save it into a file named `app.py` on your local machine.
2.  **Install Streamlit:** If you haven't already, install Streamlit in your environment:
    ```bash
    pip install streamlit
    ```
3.  **Run the app:** Open your terminal or command prompt, navigate to the directory where you saved `app.py`, and run the following command:
    ```bash
    streamlit run app.py
    ```
4.  **Access the app:** Streamlit will then open a new tab in your web browser with your interactive NLP application.
"""
